### ISSUE TITLE
屌爆了的框架! 咨询AbsFragment的使用问题。

### ISSUE THREAD

**Issue by h2oiswater** [AriaLyy/MVVM#2]
非常牛逼的框架！

我想使用AbsFragment，
于是我
`public class MainFragment extends AbsFragment<BaseViewModel>`
 
```
@Override
    protected int setLayoutId() {
        return R.layout.fragment_task;
    }
```

然后
```
public class BaseViewModel extends ViewDataBinding {


    /**
     * @param bindingComponent
     * @param root
     * @param localFieldCount
     * @hide
     */
    protected BaseViewModel(DataBindingComponent bindingComponent, View root, int localFieldCount) {
        super(bindingComponent, root, localFieldCount);
    }

    @Override
    protected boolean onFieldChange(int localFieldId, Object object, int fieldId) {
        return false;
    }

    @Override
    public boolean setVariable(int variableId, Object value) {
        return false;
    }

    @Override
    protected void executeBindings() {

    }

    @Override
    public void invalidateAll() {

    }

    @Override
    public boolean hasPendingBindings() {
        return false;
    }
}
```

一运行就报错
` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.databinding.ViewDataBinding.getRoot()' on a null object reference
                                                                               at com.arialyy.frame.core.AbsFragment.initFragment(AbsFragment.java:67)
                                                                               at com.arialyy.frame.core.AbsFragment.onCreateView(AbsFragment.java:58)
                                                                               at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                               at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                               at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                               at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                                               at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
                                                                               at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                               at android.app.Activity.performStart(Activity.java:6253)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                               at java.lang.reflect.Method.invoke(Native Method)`

**Comment by h2oiswater** [comment]
想请问AbsFragment的具体用法

**Comment by AriaLyy** [comment]
你的用法错了。ViewDataBinding是自动生成的
如: fragment_test.xml
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <FrameLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <fragment
            class="com.example.arial.mvvm.permission.PermissionFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            tools:layout="@layout/fragment_test" />
    </FrameLayout>
</layout>
在最外层添加<layout>，会自动生成FragmentTestBinding！！
然后在AbsFragment的尖括号中使用该自动生成的FragmentTestBinding！！！
public class MainFragment extends AbsFragment<FragmentTestBinding>{
       ........
}

这是谷歌dataBinding的使用方式，ViewDataBinding是不能自己写的

**Comment by h2oiswater** [comment]
谢谢大神！
