### ISSUE TITLE
混淆出错

### ISSUE THREAD

**Issue by rwz657026189** [AriaLyy/MVVM#6]
`大神，用到你的框架，混淆是按你写的，打包后运行出错。
`java.lang.NullPointerException:`Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
                                                       at com.arialyy.frame.core.AbsFragment.onActivityCreated(AbsFragment.java:86)
                                                       at com.touchrom.fanjianzhi.base.BaseFragment.onActivityCreated(BaseFragment.java:52)
                                                       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)``
好像是反射getFragmentManager（）的mContainer属性混淆了。可我加了-keepclassmembers  class \* extends  android.support.v4.app.FragmentManager{
FragmentContainer mContainer;
}依然报错，该怎么解决呀，请赐教。。感激不尽

**Comment by AriaLyy** [comment]
在你的混淆文件中增加下面两行
-dontwarn android.support.**
-keep class android.support.**{*;}

**Comment by rwz657026189** [comment]
谢谢，已解决了。还有个问题，空视图显示有点问题，在AbsFragment类中showTempView（）和hintTempView（）方法去找空视图的父容器child，实际上vp.getChildAt(0)得到的竟是position = 1 的根布局。而1得到的又是0,2得到的又是3,3得到的又是2，导致当前的空视图显示到其他界面去了。现在也没弄清楚这个原因。但是完全可以将mTempView加入到child = mRoot中。实际运行没有错。不知有没有考虑遗漏的

**Comment by AriaLyy** [comment]
位置错乱感觉是vp获取当前fragment 的position出现的问题，至于你说的“将mTempView加入到child = mRoot中”，这是什么意思？

**Comment by AriaLyy** [comment]
空视图bug已经修复，问题出在vp.getCurrentItem()这句话中，这句代码导致当前position获取不准确
